### ISSUE TITLE
Link entity not required by default

### ISSUE THREAD

**Issue by avk** [ignitionworks/draftjs_exporter#3]
Just noticed that when following the [config in the current README](https://github.com/ignitionworks/draftjs_exporter/blob/cd29b1c/README.md#usage):

```rb
config = {
  entity_decorators: {
    'LINK' => DraftjsExporter::Entities::Link.new(className: 'link')
  },
  # ...
}
```

This line 
```rb
DraftjsExporter::Entities::Link.new(className: 'link')
``` 
fails with `NameError: uninitialized constant DraftjsExporter::Entities::Link`
unless I do an explicit 
```rb
require 'draftjs_exporter/entities/link'
```

Any reason the `Link` entity shouldn't be required by default?

**Comment by theozaurus** [comment]
People may not want the Link entity which is why it's not required by default (or they may want a different type of link entity). If you can think of a way of making the documentation clearer in this respect please make a pull request.

Thanks,

Theo
